# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d23fbfd026a8fc6929630319b6229dcb904df42479a17c9562fc48378884c76984c73c792f940e8a03aed16545cf784cab2b5c10cfe65e9b8dfe865efae50280

test:
  secret_key_base: e8b33babd88ad97cd64d8f02bac2ae9c1ab4aac2083c2c1a8432da8a89cdb41cdc602de747e2bf5dcc94a213edc0c0bcb89a28d96ad3bdf08db8b3dff1012874

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
